# 예외 처리 (Exception Handling)

프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우에 이러한 결과를 초래하는 원인을 `에러` 또는 `오류` 라고한다. 

이는 발생시점에 따라 `컴파일에러` 또는 `런타임에러`로 나눌 수 있다.

- 컴파일 에러
  - 컴파일 할 때 발생하는 에러
- 런타임 에러
  - 프로그램의 실행 도중에 발생하는 에러 
- (논리적 에러)
  - 실행은 되지만 의도와 다르게 동작하는 것



```
소스코드를 컴파일하면  컴파일러가 소스코드(.java)에 대해 오타, 잘못된 구문, 자료형 체크 등의 기본적인 검사를 수행하여 오류가 있는지 알려준다
컴파일이 성공적으로 완료되면 클래스파일(.class)이 생성되고, 생성된 클래스파일을 실행할 수 있게 된다.

실행도중에 발생할 수 있는 잠재적인 오류로 인해 컴파일은 잘 되었어도 프로그램이 비정상적으로 종료될 수 있다. 
런타임 에러를 방지하기 위해서 프로그램의 실행 도중 발생할 수 있는 모든 공유의 수를 고려하여 이에 대한 대비를 해야한다.
```



자바에서는 실행시 발생할 수 있는 프로그램 오류를 `에러` 와 `오류` 로 구분한다.   

- 에러 (Error)
  - 메모리 부족(OutOfMemoryError)나 스택오버플로우(StackOverflowError)와 같이 일단 발생하면 복구할 수 없는 심각한 오류
  - 프로그램의 비정상적인 종료를 막을 수 없음
- 예외 (Exception)
  - 발생하더라도 수습될 수 있는 비교적 덜 심각한 것 
  - 프로그래머가 이에 대한 적절한 코드를 미리 작성해 놓음으로써 프로그램의 비정상적인 종료를 막음



## 예외 클래스의 계층 구조

자바는 실행 시 발생할 수 있는 오류(Exception과 Error)를 클래스로 정의하였다. 

![dlall](http://www.tcpschool.com/lectures/img_java_exception_class_hierarchy.png). 

<그림 출처 TCPSCHOOL >   

모든 클래스의 조상은 Object 클래스이므로 Exception클래스와 Error클래스 모두 Object의 자손이다.  

모든 예외의 최고 조상은 Exception클래스이고, 예외 클래스는 두 그룹으로 나눠질 수 있다.

- Exception클래스와 그 자손들(RuntimeException제외) : `Exception클래스들`

  - **CheckedException**, 반드시 try, catch, throw를 통해 예외처리를 해주어야함 
  - *외부의 영향*으로 발생할 수 있음 
  - 프로그램 사용자들의 동작, 실수에 의해 발생 
  - ex)
    - 존재하지 않는 파일의 이름 입력 (FileNotFoundException)
    - 실수로 클래스 이름 잘못 적음 ( ClassNotFoundException)
    - 입력 데이터 형식이 잘못됨 (DataFormatException)

- RuntimeException클래스와 그 자손들 : `RuntimeException클래스들`

  - **UncheckedException**, 명시적으로 처리하지 않아도 되는 예외, 예외처리를 강제하지 않음 

    - 만약 UncheckedException의 예외처리를 강제했다면 단순히 배열을 참조할 때도 혹시 배열의 범위를 벗어날 수 있으니 매번 try catch로 적어줘야했을 것임 

  - 주로 *프로그래머의 실수*에 의해 발생될 수 있는 예외들 

  - ex) 

    - 배열의 범위를 벗어남 (ArrayIndexOutOfBoundsException)

    - 값이 null인 참조 변수 멤버 호출(NullPointerException)

    - 클래스간 잘못된 형변환 (ClassCastException)

    - 정수를 0으로 나눔 (ArithmeticException)

      

## 예외 처리 - try-catch

예외처리란 프로그램 실행시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행중인 프로그램의 갑작스런 비정상종료를 막고 정상적인 실행상태를 유지할 수 있도록 하는것이다.  

발생한 예외를 처리하지 못하면 프로그램은 비정상적으로 종료되며 처리되지 못한 예외는 JVM의 예외처리기(UncaughtExceptionHandler)가 받아서 예외의 원인을 화면에 출력한다.   



예외를 처리하기 위해서는 try-catch문을 사용 

```java
try {
  //예외가 발생할 가능성이 있는 문장
} catch (Exception1 e1){
  //Exception1이 발생했을 경우 이를 처리하기 위한 문장
} catch (Exception2 e1){
  //Exception2이 발생했을 경우 이를 처리하기 위한 문장
} ...
```

하나의 try블럭 다음에 여러 종류의 예외를 처리하는 하나 이상의 catch 블럭이 존재하고 발생한 예외는 단 한개의 catch블럭만 수행된다.  



```java
class ExceptionEx {
  public static void main(String args[]) {
    int number = 100;
    int result = 0;
    for(int i=0; i<10; i++){
      try {
        result = number/ (int)(Math.random() * 10);
        System.out.println(result);
      } catch (ArithmeticException e) { // --> Math.random()에 0이 나오면 ArithmeticException이 발생하여 catch 부분이 수행될 것 
        System.out.println("0");
      } // try-catch end
    } // for end 
  }
}

// 실행결과 예시
/*
16
20
11
0 <- 예외발생처리
...
*/
```

모든 예외 클래스는 Exception클래스의 자손이므로 catch블럭의 괄호에 Exception클래스 타입의 참조변수를 선언하면 어떤 종류의 예외가 발생하더라도 catch블럭에서 처리된다. 

catch블럭에 `|` 사용해서 형제관계에 있는 에러들 멀티로 사용할 수 있음 



### printStackTrace(), getMessage()

예외가 발생했을 때 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨있으며 getMessage(), printStackTrace()를 통해 이 정보를 얻을 수 있다.   

- printStackTrace()
  - 예외발생 당시의 호출 스택(Call Stack)에 있었던 메서드의 정보와 예외 메세지 화면에 출력
- getMessage()
  - 발생한 예외클래스의 인스턴스에 저장된 메시지 



## 예외 발생시키기 - throw

`throw를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있다. 

```java
1. 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만듦
2. 키워드 throw를 이용해 예외를 발생 

Exception e = new Exception("고의로 발생시킨 예외");
throw e;
// throw new Exception("고의로 예외 발생 한줄로 생성과 throw");

Exception생성할 때 생성자에 String을 넣어주면 e.getMessage()로 확인 가능 
```



## 메서드에 예외 선언 - throws

메서드에 예외를 선언하려면, 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어주면 된다.  이 때 선언하면 예외 뿐 아니라 자손 타입의 예외까지도 발생할 수 있다는 점은 주의해야한다.  

```java
void method() throws Exception1, Exception2 ... ExceptionN {
  //
}
```



메서드의 선언부에 예외를 선언함으로써 메서드를 사용하려는 사람이 메서드의 선언부를 보았을 때 이 메서드를 사용하기 위해서는 어떠한 예외들이 처리되어야 하는지를 쉽게 알 수 있다. 자바에서는 메서드를 작성할 때 메서드 내에 발생할 가능성이 있는 예외를 메서드의 선언부에 명시하여 이 메서드를 사용하는 쪽에서 이에대한 처리를 하도록 강요하여 견고한 코드를 작성할 수 있도록 도와준다.  

throws로 예외를 명시하는 것은 자신을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것.  



## finally블럭

- 예외 발생 여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용
- try-catch문의 끝에 덧붙여서 사용
- 예외 발생한 경우 try - catch - finally
- 예외 발생하지 않은 경우 try- finally



## 자동 자원 반환 - try-with-resources

JDK 1.7부터 지원

```java
try( FileInputStream fis = new FileInputStream("score.dat"); ) {

}
```

괄호 안에 객체 생성 문장을 넣으면 객체는 따로 close를 호출하지 않아도 자동적으로 try를 벗어날 때 close가 호출됨. 예외 발생시 Supressed로 표시되는 예외 추가로 출력..



## 사용자 정의 예외 만들기

보통 Exception 또는 RuntimeException클래스로부터 상속 받아 클래스 생성, 가능하면 새로운 예외 클래스보다 기존의 예외 클래스 활용하는 것이 좋다. 

메시지 뿐 아니라 에러코드 값도 저장하고 getErrCode() 메서드도 클래스의 멤버로 추가하여 Exception발생시 getMessage, getErrCode()사용할 수 있음. 

```java
class MyException extends Exception {
  private final int ERR_CODE;
  
  MyException(String msg, int errCode) { // 생성자
    super(msg); 
    ERR_CODE = errCode;
  }
  MyException(String msg) { // 생성자
    this(msg,100); //기본 에러코드
  }
  public int getErrCode(){
    return ERR_CODE;
  }
}
```



## chained Exception 연결된 예외

한 예외가 다른 예외를 발생시킬 수도 있다. 예외 A가 예외 B를 발생시켰다면 A를 B의 원인예외(cause exception)이라고 한다.  

```java
try {
  statInstall(); //SpaceException발생
  copyFiles();
}catch (SpaceException e) {
  InstallException ie = new InstallException("설치중 예외 발생");// 예외 생성
  ie.initCause(e); // 원인예외지정
  throw ie;
} catch () {
  ...
}
```

initCause()는 Exception클래스의 조상인 `Throwable` 클래스에 정의되어 모든 예외에서 사용 가능하다. 

```java
Throwable initCause(Throwable cause) //지정한 예외를 원인예외로 등록
Throwable getCause() // 원인 예외 반환 
```

checkedException을 unchekcedException으로 바꾸기 위해서도 사용.강제하지 않으려고 

```java
RuntimeException(Throwable cause);
throw new RuntimeException(new MemoryException(""));
```

